import Head from "next/head";
import RoiCalculator from "@/components/roi-calculator";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const {
    fractionCost,
    plusvalia,
    airbnbNightCost,
    percentageOccupationEstimation,
    years,
  } = router.query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*@ts-ignore */}
      <RoiCalculator
        fractionCost={parseFloat((fractionCost as string) || "390000")}
        plusvalia={parseFloat((plusvalia as string) || "0.12")}
        airbnbNightCost={parseFloat((airbnbNightCost as string) || "3000")}
        percentageOccupationEstimation={parseFloat(
          (percentageOccupationEstimation as string) || "0.62"
        )}
        years={parseFloat((years as string) || "5")}
      />
    </>
  );
}
